version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8080"
    restart: unless-stopped

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    env_file:
      - .env
    ports:
      - "8001:8001"
    restart: unless-stopped

networks:
  default:
    driver: bridge